dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

env:
  global:
    - DJF_USERNAME=postgres

services:
  - postgresql

install: travis_retry pip install coveralls tox-travis

before_script:
  - psql -c 'create database djftest;' -U postgres

script: tox

after_success: coveralls
