language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

env:
  global:
    - DJF_USERNAME=postgres
  # Keep this list up to date using `tox -l`
  matrix:
    - TOXENV=pypy-django18-mysql
    - TOXENV=pypy-django18-pg
    - TOXENV=pypy-django18-sqlite
    - TOXENV=pypy-django110-mysql
    - TOXENV=pypy-django110-pg
    - TOXENV=pypy-django110-sqlite
    - TOXENV=py27-django18-mysql
    - TOXENV=py27-django18-pg
    - TOXENV=py27-django18-sqlite
    - TOXENV=py27-django110-mysql
    - TOXENV=py27-django110-pg
    - TOXENV=py27-django110-sqlite
    - TOXENV=py33-django18-pg
    - TOXENV=py33-django18-mysql
    - TOXENV=py33-django18-sqlite
    - TOXENV=py33-django110-pg
    - TOXENV=py33-django110-sqlite
    - TOXENV=py33-django110-mysql
    - TOXENV=py34-django18-pg
    - TOXENV=py34-django18-sqlite
    - TOXENV=py34-django18-mysql
    - TOXENV=py34-django110-pg
    - TOXENV=py34-django110-sqlite
    - TOXENV=py34-django110-mysql
    - TOXENV=py34-djangotrunk-pg
    - TOXENV=py34-djangotrunk-mysql
    - TOXENV=py34-djangotrunk-sqlite
    - TOXENV=py35-djangotrunk-pg
    - TOXENV=py35-djangotrunk-sqlite
    - TOXENV=py35-djangotrunk-mysql
    - TOXENV=py36-djangotrunk-pg
    - TOXENV=py36-djangotrunk-sqlite
    - TOXENV=py36-djangotrunk-mysql
    - TOXENV=flake8
    - TOXENV=docs

install: travis_retry pip install tox coveralls

script: tox -e $TOXENV

after_success: coveralls
